#!/bin/bash
# GitHub PR 推送脚本

echo "=== Tennis 项目 PR 推送助手 ==="
echo ""
echo "你的代码已准备好推送！"
echo "当前分支: feature/video-playback-controls"
echo ""
echo "请按以下步骤操作："
echo ""
echo "1. 确保你已创建 GitHub Personal Access Token"
echo "   访问: https://github.com/settings/tokens"
echo "   点击 'Generate new token (classic)'"
echo "   勾选 'repo' 权限"
echo ""
echo "2. 使用以下命令推送（将 YOUR_TOKEN 替换为你的 token）："
echo ""
echo "   git remote set-url origin https://YOUR_TOKEN@github.com/shenstone-peng/Tennis.git"
echo "   git push -u origin feature/video-playback-controls"
echo ""
echo "3. 推送成功后，创建 PR："
echo "   访问: https://github.com/shenstone-peng/Tennis/pull/new/feature/video-playback-controls"
echo ""
echo "或者直接运行："
echo "   open https://github.com/shenstone-peng/Tennis/pull/new/feature/video-playback-controls"
echo ""
echo "=== PR 信息建议 ==="
echo "标题: feat: Add video playback controls and frame-by-frame navigation"
echo ""
echo "描述:"
echo "This PR implements video playback functionality with the following features:"
echo ""
echo "- Fix video playback by properly connecting video elements to refs"
echo "- Add independent seek controls for left and right videos"
echo "- Add frame-by-frame navigation with wheel and button controls"
echo "- Add adjustable frame sensitivity (1-10x)"
echo "- Move control panel to non-sticky position to avoid overlapping video content"
echo "- Add independent duration tracking for both videos"
echo ""
echo "测试步骤:"
echo "1. 上传左右两个视频"
echo "2. 点击播放按钮测试同步播放"
echo "3. 使用 Frame Control 区域的左右按钮测试逐帧导航"
echo "4. 调整灵敏度测试不同步长"
echo "5. 分别拖动左右视频的进度条测试独立控制"
